name: SEO & Smoke Checks

on:
  pull_request:
    paths:
      - "index.html"
      - "fr/index.html"
      - "explain/**"
      - "fr/expliquer/**"
      - "sitemap.xml"
      - "robots.txt"
      - "vercel.json"
      - "scripts/**"
  workflow_dispatch:

jobs:
  spdx_fix:
    name: SPDX quick-fix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - run: npm i globby@14
      - name: Run SPDX fixer
        run: node scripts/spdx-fix.cjs

  warmup:
    runs-on: ubuntu-latest
    needs: spdx_fix
    steps:
      - name: Warm up site
        run: |
          set -e
          URL="https://documate.work/"
          for i in 1 2 3 4 5; do
            code=$(curl -sS -o /dev/null -w "%{http_code}" "$URL")
            [ "$code" = "200" ] && exit 0
            echo "Warmup try $i got $code, retrying..."
            sleep 3
          done
          echo "Error: Unexpected status $code for $URL"
          exit 1

  assets:
    runs-on: ubuntu-latest
    needs: warmup
    steps:
      - name: Check assets return 200
        run: |
          set -e
          for u in \
            "https://documate.work/sitemap.xml" \
            "https://documate.work/robots.txt" \
            "https://documate.work/explain/bill/" \
            "https://documate.work/explain/contract/" \
            "https://documate.work/fr/expliquer/facture/" \
            "https://documate.work/fr/expliquer/contrat/"
          do
            code=$(curl -sS -o /dev/null -w "%{http_code}" "$u")
            [ "$code" = "200" ] || { echo "Unexpected $code for $u"; exit 1; }
          done

  smoke:
    name: Smoke
    runs-on: ubuntu-latest
    needs: assets
    timeout-minutes: 7
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Cache Puppeteer Chromium
        uses: actions/cache@v4
        with:
          path: ~/.cache/puppeteer
          key: puppeteer-${{ runner.os }}-v1
      - name: Installer Puppeteer (sans Playwright)
        run: |
          set -e
          # Ne rien installer de Playwright. On force Puppeteer uniquement :
          npm pkg delete devDependencies."@playwright/test" 2>/dev/null || true
          npm pkg delete dependencies."@playwright/test" 2>/dev/null || true
          npm pkg delete devDependencies."playwright" 2>/dev/null || true
          npm pkg delete dependencies."playwright" 2>/dev/null || true
          npm i puppeteer@22
      - name: Lancer les smoke checks
        env:
          NODE_OPTIONS: "--max-old-space-size=512"
        run: node scripts/seo-smoke.cjs "https://documate.work/"

  lighthouse:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    needs: smoke
    steps:
      - uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            https://documate.work/
            https://documate.work/explain/bill/
          uploadArtifacts: false
          runs: 1
