name: SPDX check
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure SPDX headers
        run: |
          set -e
          MISS=0
          while IFS= read -r -d '' f; do
            case "$f" in
              */node_modules/*|*/vendor/*|*/dist/*|*/build/*) continue;;
              *.html|*.js|*.css) ;;
              *) continue;;
            esac
            if ! grep -q "SPDX-License-Identifier: LicenseRef-SA-NC-1.0" "$f"; then
              echo "Missing SPDX in $f"; MISS=1
            fi
          done < <(find . -type f -print0)
          exit $MISS
